### ISSUE TITLE
 which is the author's test source code for low-light image enhancement in fig12? 

### ISSUE THREAD

**Issue by GY5134** [csjunxu/STAR-TIP2020#1]
Dear author, your article has solved my doubts for many years, but there is a question I need to ask you. which is the author's test source code for low-light image enhancement in fig12? Please let me know.

**Comment by csjunxu** [comment]
Please use 

https://github.com/csjunxu/STAR-TIP2020/blob/master/Demo_Illumination.m

The images are from the described datasets.
